### ISSUE TITLE
Unhandled Exception: System.NullReferenceException

### ISSUE THREAD

**Issue by Duoquadragesimal** [Sevenanths/dolphiilution-csharp#1]
`Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at UniversalISOBuilder.RiivolutionUniversalISOBuilder.doStuff(String ISOPath, String xmlPath, String rootPath, String outPath, String singleChoice, String newTitleID, Boolean isSilent, Boolean deleteISO)
   at UniversalISOBuilder.RiivolutionUniversalISOBuilder.Main(String[] args)
   at UniversalISOBuilder.Program.Main(String[] args)`

**Comment by Duoquadragesimal** [comment]
wait sorry this is the wrong repo

**Comment by Duoquadragesimal** [comment]
closing
